### ISSUE TITLE
GH action for production release fails with fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by jpbnetley** [jpbnetley/npm-version-release-action#1]
when getting to the step to merge release branch down to pre-release.
The pr creation fails with
```
Run release_branch_name=dev
  release_branch_name=dev
  pre_branch_name=dev
  gh pr create --base $pre_branch_name --head $release_branch_name --title "Merge $release_branch_name into $pre_release_branch_name after release" --body "Merging $release_branch_name into $release_branch_name" --assignee jpbnetley
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_TOKEN: ***
failed to run git: fatal: not a git repository (or any of the parent directories): .git
```

**Comment by jpbnetley** [comment]
Most likely because the shared action doesn't know to what repo the pr should be made.
need to infer the repo name if possible, or add it as an input

**Comment by jpbnetley** [comment]
```yml
run: |
        release_branch_name=${{ inputs.deployment_branch_name }}
        pre_branch_name=${{ inputs.pre_release_branch_name }}
        gh pr create --base $pre_branch_name --head $release_branch_name --title "Merge $release_branch_name into $pre_release_branch_name after release" --body "Merging $release_branch_name into $pre_branch_name" --assignee ${{ github.actor }}
  env:
       GH_TOKEN: ${{ secrets.GH_PAT }}
  working-directory:  ${{ inputs.repo }}
```
